/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "GestorBiblioteca.h"
#include <stdlib.h>
#include <time.h>
#include <string.h>
#include <stdio.h>
#include <ctype.h>

#define Cls system("clear")
#define Pause system("read -p \"Pulsa una tecla para continuar..... \" a")
#define MostrarAviso(Texto) \
	{                       \
		printf(Texto);      \
		Pause;              \
	}

void gestorbiblioteca_1(char *host)
{
	CLIENT *clnt;
	int *result_1;
	char conexion_1_arg;
	bool_t *result_2;
	int desconexion_1_arg;
	int *result_3;
	TConsulta cargardatos_1_arg;
	bool_t *result_4;
	int guardardatos_1_arg;
	int *result_5;
	TNuevo nuevolibro_1_arg;
	int *result_6;
	TComRet comprar_1_arg;
	int *result_7;
	TComRet retirar_1_arg;
	bool_t *result_8;
	TOrdenacion ordenar_1_arg;
	int *result_9;
	int nlibros_1_arg;
	int *result_10;
	TConsulta buscar_1_arg;
	TLibro *result_11;
	TPosicion descargar_1_arg;
	int *result_12;
	TPosicion prestar_1_arg;
	int *result_13;
	TPosicion devolver_1_arg;

#ifndef DEBUG
	clnt = clnt_create(host, GESTORBIBLIOTECA, GESTORBIBLIOTECA_VER, "tcp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */

	result_1 = conexion_1(&conexion_1_arg, clnt);
	if (result_1 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	result_2 = desconexion_1(&desconexion_1_arg, clnt);
	if (result_2 == (bool_t *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	result_3 = cargardatos_1(&cargardatos_1_arg, clnt);
	if (result_3 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	result_4 = guardardatos_1(&guardardatos_1_arg, clnt);
	if (result_4 == (bool_t *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	result_5 = nuevolibro_1(&nuevolibro_1_arg, clnt);
	if (result_5 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	result_6 = comprar_1(&comprar_1_arg, clnt);
	if (result_6 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	result_7 = retirar_1(&retirar_1_arg, clnt);
	if (result_7 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	result_8 = ordenar_1(&ordenar_1_arg, clnt);
	if (result_8 == (bool_t *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	result_9 = nlibros_1(&nlibros_1_arg, clnt);
	if (result_9 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	result_10 = buscar_1(&buscar_1_arg, clnt);
	if (result_10 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	result_11 = descargar_1(&descargar_1_arg, clnt);
	if (result_11 == (TLibro *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	result_12 = prestar_1(&prestar_1_arg, clnt);
	if (result_12 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	result_13 = devolver_1(&devolver_1_arg, clnt);
	if (result_13 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
}

struct BookValidationResult {
	bool_t validation_result;
	Cadena error;
};

typedef struct BookValidationResult BookValidationResult;

int MenuPrincipal()
{
	int Salida;
	do
	{
		Cls;
		printf(" GESTOR BIBLIOTECARIO 1.0 (M. PRINCIPAL)\n");
		printf("*****************************************\n");
		printf("\t1.- M. Administración\n");
		printf("\t2.- Consulta de libros\n");
		printf("\t3.- Prestamos libros\n");
		printf("\t4.- Devolver libros\n");
		printf("\t0.- Salir\n\n");
		printf(" Elige opción: ");
		scanf("%d", &Salida);
		if (Salida < 0 || Salida > 4)
			MostrarAviso("\n\n *** Error en la entrada de Datos.***\n\n");
	} while (Salida < 0 || Salida > 5);
	return Salida;
}

int MenuAdministracion()
{
	int Salida;
	do
	{
		Cls;
		printf(" GESTOR BIBLIOTECARIO 1.0 (M. ADMINISTRACION)\n");
		printf("**********************************************\n");
		printf("\t1.- Cargar datos Biblioteca\n");
		printf("\t2.- Guardar datos Biblioteca\n");
		printf("\t3.- Nuevo libro\n");
		printf("\t4.- Comprar libros\n");
		printf("\t5.- Retirar libros\n");
		printf("\t6.- Ordenar libros\n");
		printf("\t7.- Buscar libros\n");
		printf("\t8.- Listar libros\n");
		printf("\t0.- Salir\n\n");
		printf(" Elige opción: ");
		scanf("%d", &Salida);
		if (Salida < 0 || Salida > 8)
			MostrarAviso("\n\n *** Error en la entrada de Datos.***\n\n");
	} while (Salida < 0 || Salida > 8);
	return Salida;
}

void Formatea(char *Salida, const char *p, int ancho, char Caracter)
{
	Cadena vacia;
	int len = ancho - strlen(p);
	int l = 0, c = 0;

	while (p[l] != '\0')
	{
		if ((unsigned char)p[l] > 128)
			c++;
		l++;
	}
	len += c / 2;

	if (len < 0)
		len = 0;
	for (int i = 0; i < len; i++)
		vacia[i] = Caracter;
	vacia[len] = '\0';

	sprintf(Salida, "%s%s", p, vacia);
}

void MostrarLibro(TLibro *L, int Pos, bool_t Cabecera)
{
	Cadena T, A, B, PI;
	if (Cabecera == TRUE)
	{
		printf("%-*s%-*s%-*s%*s%*s%*s\n", 5, "POS", 58, "TITULO", 18, "ISBN", 4, "DIS", 4, "PRE", 4, "RES");
		printf("     %-*s%-*s%-*s\n", 30, "AUTOR", 28, "PAIS (IDIOMA)", 12, "AÑO");
		Formatea(B, "*", 93, '*');
		printf("%s\n", B);
	}
	Formatea(T, L->Titulo, 58, ' ');
	Formatea(A, L->Autor, 30, ' ');
	strcpy(B, L->Pais);
	strcat(B, " (");
	strcat(B, L->Idioma);
	strcat(B, ")");
	Formatea(PI, B, 28, ' ');
	printf("%-5d%s%-*s%*d%*d%*d\n", Pos + 1, T, 18, L->Isbn, 4, L->NoLibros, 4, L->NoPrestados, 4, L->NoListaEspera);
	printf("     %s%s%-*d\n", A, PI, 12, L->Anio);
}

void handleAdminMenuOption0(int id_admin, CLIENT *clnt)
{
	bool_t *disconnection_result = desconexion_1(&id_admin, clnt);

	if (disconnection_result == (bool_t *)NULL)
	{
		clnt_perror(clnt, "La llamada a la función ha fallado\n");
		Pause;
		return;
	}

	if (*disconnection_result == TRUE)
	{
		printf("Administrador desconectado\n");
		Pause;
	}
	else if (*disconnection_result == FALSE)
	{
		printf("ID de administrador no coincide con la alojada en el servidor, \
					se procederá a cerrar su sesión\n");
		Pause;
		exit(1);
	}
}

void handleAdminMenuOption1(int id_admin, CLIENT *clnt)
{
	Cls;

	Cadena file_name;

	printf("Introduce el nombre del fichero de datos: ");
	__fpurge(stdin);
	scanf("%s", file_name);

	TConsulta query;
	query.Ida = id_admin;
	strcpy(query.Datos, file_name);

	int *result = cargardatos_1(&query, clnt);

	if (result == (int *)NULL)
	{
		clnt_perror(clnt, "La llamada a la función ha fallado\n");
		Pause;
		return;
	}

	if(*result == -1)
	{
		printf("Ya hay un usuario identificado como administrador, o bien el ID de administrador " \
		"no coincide.\n");
		Pause;
	}
	else if(*result == 0)
	{
		printf("Error al cargar los datos de la biblioteca\n");
		Pause;
	}
	else if(*result == 1)
	{
		printf("** La biblioteca ha sido cargada **\n");
		Pause;
	}
}

void handleAdminMenuOption2(int id_admin, CLIENT *clnt)
{
	Cls;

	int *number_of_books = nlibros_1(&id_admin, clnt);

	if (number_of_books == (int *)NULL)
	{
		clnt_perror(clnt, "La llamada a la función ha fallado\n");
		Pause;
		return;
	}

	if(*number_of_books == 0)
	{
		printf("Error: No hay libros cargados en la biblioteca. " \
		"No se han guardado los datos.\n");
		Pause;
		return;
	}

	bool_t *result = guardardatos_1(&id_admin, clnt);

	if (result == (bool_t *)NULL)
	{
		clnt_perror(clnt, "La llamada a la función ha fallado\n");
		Pause;
		return;
	}

	if(*result == FALSE)
	{
		printf("Error: No se han podido guardar los datos de la biblioteca\n");
		Pause;
	}
	else
	{
		printf("** Se ha guardado el estado actual de la biblioteca **\n");
		Pause;
	}
}

bool_t is_empty(char *string)
{
	if(strlen(string) == 0)
	{
		return TRUE;
	}

	return FALSE;
}

bool_t is_blank(char *string)
{
	if(is_empty(string) == TRUE)
	{
		return TRUE;
	}

	int length = strlen(string);
	
	bool_t is_blank = TRUE;

	for (int i = 0; i < length; i++)
	{
		if(!isspace(string[i]))
		{
			is_blank = FALSE;
			break;
		}
	}
	
	return is_blank;
}

BookValidationResult validateBook(TLibro book)
{
	BookValidationResult book_validation_result;

	if(is_empty(book.Isbn) || is_blank(book.Isbn))
	{
		book_validation_result.validation_result = FALSE;
		strcpy(book_validation_result.error, "No se ha introducido ISBN");
		return book_validation_result;
	}

	if(is_empty(book.Titulo) || is_blank(book.Titulo))
	{
		book_validation_result.validation_result = FALSE;
		strcpy(book_validation_result.error, "El titulo del libro no es válido");
		return book_validation_result;
	}

	if(is_empty(book.Autor) || is_blank(book.Autor))
	{
		book_validation_result.validation_result = FALSE;
		strcpy(book_validation_result.error, "El autor introducido no es válido");
		return book_validation_result;
	}

	if(book.Anio < 0)
	{
		book_validation_result.validation_result = FALSE;
		strcpy(book_validation_result.error, "El año introducido no es válido");
		return book_validation_result;
	}

	if(is_empty(book.Pais) || is_blank(book.Pais))
	{
		book_validation_result.validation_result = FALSE;
		strcpy(book_validation_result.error, "El país introducido no es válido");
		return book_validation_result;
	}

	if(is_empty(book.Idioma) || is_blank(book.Idioma))
	{
		book_validation_result.validation_result = FALSE;
		strcpy(book_validation_result.error, "El idioma introducido no es válido");
		return book_validation_result;
	}

	//At least one book must be available
	if(book.NoLibros <= 0)
	{
		book_validation_result.validation_result = FALSE;
		strcpy(book_validation_result.error, "El nº de libros introducido no es válido");
		return book_validation_result;
	}

	if(book.NoPrestados < 0)
	{
		book_validation_result.validation_result = FALSE;
		strcpy(book_validation_result.error, "El nº de ejemplares prestados introducido no es válido");
		return book_validation_result;
	}

	if(book.NoListaEspera < 0)
	{
		book_validation_result.validation_result = FALSE;
		strcpy(book_validation_result.error, "El nº de ejemplares en lista de espera introducido no es válido");
		return book_validation_result;
	}

	book_validation_result.validation_result = TRUE;
	strcpy(book_validation_result.error, "");

	return book_validation_result;
}

void handleAdminMenuOption3(int id_admin, CLIENT *clnt)
{
	Cls;

	Cadena isbn;
	Cadena author;
	Cadena title;
	int year;
	Cadena country;
	Cadena language;
	int number_of_books;

	printf("Introduce el Isbn: ");
	__fpurge(stdin);
	scanf("%s", isbn);

	printf("Introduce el Autor: ");
	__fpurge(stdin);
	scanf("%s", author);

	printf("Introduce el Título: ");
	__fpurge(stdin);
	scanf("%s", title);

	printf("Introduce el año: ");
	__fpurge(stdin);
	scanf("%d", &year);

	printf("Introduce el País: ");
	__fpurge(stdin);
	scanf("%s", country);

	printf("Introduce el Idioma: ");
	__fpurge(stdin);
	scanf("%s", language);

	printf("Introduce el Número de Libros Inicial: ");
	__fpurge(stdin);
	scanf("%d", &number_of_books);

	TLibro book;
	
	strcpy(book.Isbn, isbn);
	strcpy(book.Autor, author);
	strcpy(book.Titulo, title);
	book.Anio = year;
	strcpy(book.Pais, country);
	strcpy(book.Idioma, language);
	book.NoLibros = number_of_books;
	book.NoPrestados = 0;
	book.NoListaEspera = 0;

	BookValidationResult book_validation_result = validateBook(book);

	//FALSE means that there has been an error
	if(book_validation_result.validation_result == FALSE)
	{
		printf("ISBN: %s\n", book.Isbn);
		printf("Autor: %s\n", book.Autor);
		printf("Titulo: %s\n", book.Titulo);
		printf("Anio: %d\n", book.Anio);
		printf("Pais: %s\n", book.Pais);
		printf("Idioma: %s\n", book.Idioma);
		printf("N libros: %d\n", book.NoLibros);

		printf("Error: %s\n", book_validation_result.error);
		Pause;
		return;
	}

	TNuevo new_book;
	
	new_book.Ida = id_admin;
	new_book.Libro = book;

	int *result = nuevolibro_1(&new_book, clnt);

	if (result == (int *)NULL)
	{
		clnt_perror(clnt, "La llamada a la función ha fallado\n");
		Pause;
		return;
	}

	if(*result == -1)
	{
		printf("Error: ya hay un usuario identificado como administrador o el Ida no coincide con el almacenado en el servidor\n");
		Pause;
	}
	else if(*result == 0)
	{
		printf("Error: Hay un libro en el vector dinámico que tiene el mismo Isbn\n");
		Pause;
	}
	else if(*result == 1)
	{
		printf("Se ha añadido el nuevo libro con éxito\n");
		Pause;
	}
	else if(*result == -2)
	{
		printf("Error: No hay ninguna biblioteca cargada\n");
		Pause;
	}
}

void handleAdminMenuOption4(int id_admin, CLIENT *clnt)
{
	Cls;

	int *number_of_books = nlibros_1(&id_admin, clnt);

	if (number_of_books == (int *)NULL)
	{
		clnt_perror(clnt, "La llamada a la función ha fallado\n");
		Pause;
		return;
	}

	if(*number_of_books == 0)
	{
		printf("No hay libros cargados en la biblioteca.\n");
		Pause;
		return;
	}

	Cadena isbn;

	printf("Introduce ISBN a buscar: ");
	__fpurge(stdin);
	scanf("%s", isbn);

	TConsulta search_book;
	strcpy(search_book.Datos, isbn);
	search_book.Ida = id_admin;

	int *book_position = buscar_1(&search_book, clnt);

	if (book_position == (int *)NULL)
	{
		clnt_perror(clnt, "La llamada a la función ha fallado\n");
		Pause;
		return;
	}

	if(*book_position == -1)
	{
		printf("Error: No se ha encontrado ningún libro con el ISBN indicado.\n");
		Pause;
		return;
	}

	if(*book_position == -2)
	{
		printf("Error: Ya hay un usuario identificado como administrador." \
		" O bien el ID no coincide con el almacenado en el servidor\n");
		Pause;
		return;
	}

	if(*book_position == -3)
	{
		printf("Error: No hay biblioteca cargada actualmente.\n");
		Pause;
		return;
	}

	TPosicion book_position_struct;
	book_position_struct.Ida = id_admin;
	book_position_struct.Pos = *book_position;

	TLibro *book = descargar_1(&book_position_struct, clnt);

	if (book == (TLibro *)NULL)
	{
		clnt_perror(clnt, "La llamada a la función ha fallado\n");
		Pause;
		return;
	}

	MostrarLibro(book, *book_position, TRUE);

	char buy_books_or_not;

	printf("¿Es este el libro del que deseas comprar más unidades? (s/n): ");
	__fpurge(stdin);
	scanf("%c", &buy_books_or_not);

	if(buy_books_or_not == 's' || buy_books_or_not == 'S')
	{
		int books_bought;

		do
		{
			printf("Introduce número de libros comprados: ");
			__fpurge(stdin);
			scanf("%d", &books_bought);

			if(books_bought <= 0)
			{
				printf("El número de libros comprados debe ser mayor que 0\n");
			}

		} while (books_bought <= 0);
		
		TComRet buy_book;
		buy_book.Ida = id_admin;
		strcpy(buy_book.Isbn, isbn);
		buy_book.NoLibros = books_bought;

		int *buy_result = comprar_1(&buy_book, clnt);

		if (buy_result == (int *)NULL)
		{
			clnt_perror(clnt, "La llamada a la función ha fallado\n");
			Pause;
			return;
		}

		if(*buy_result == -1)
		{
			printf("Error: Ya hay un usuario identificado como administrador." \
			" O bien el ID no coincide con el almacenado en el servidor\n");
			Pause;
			return;
		} 
		else if(*buy_result == 0)
		{
			printf("Error: No hay un libro en la biblioteca que contenga el mismo ISBN\n");
			Pause;
			return;
		}
		else if(*buy_result == 1)
		{
			printf("** Se han añadido los nuevos libros **\n");
			Pause;
			return;
		}
	}
	else
	{
		printf("** Operación de compra abortada **\n");
		Pause;
		return;
	}

}

void handleAdminMenuOption8(int id_admin, CLIENT *clnt)
{
	Cls;

	int *number_of_books = nlibros_1(&id_admin, clnt);

	if (number_of_books == (int *)NULL)
	{
		clnt_perror(clnt, "La llamada a la función ha fallado\n");
		Pause;
		return;
	}

	if(*number_of_books == 0)
	{
		printf("No hay libros cargados en la biblioteca.\n");
		Pause;
		return;
	}

	printf("Libros en la biblioteca: %d\n", *number_of_books);

	TPosicion position;
	position.Ida = id_admin;

	for (int i = 0; i < *number_of_books; i++)
	{
		position.Pos = i;

		TLibro *book = descargar_1(&position, clnt);

		if (book == (TLibro *)NULL)
		{
			clnt_perror(clnt, "La llamada a la función ha fallado\n");
			Pause;
			return;
		}

		if(i == 0)
		{
			MostrarLibro(book, i, TRUE);
		}
		else
		{
			MostrarLibro(book, i, FALSE);
		}
	}
	
	Pause;
}

void handleMainMenuOption1(CLIENT *clnt)
{
	Cls;

	Cadena password;

	printf("Por favor inserte la contraseña de Administración: ");
	__fpurge(stdin);
	scanf("%s", password);

	int *connection_result = conexion_1(&password, clnt);

	if (connection_result == (int *)NULL)
	{
		clnt_perror(clnt, "La llamada a la función ha fallado\n");
		Pause;
		return;
	}

	if (*connection_result == -1)
	{
		printf("Ya existe un usuario identificado como administrador\n");
		Pause;
	}
	else if (*connection_result == -2)
	{
		printf("Contraseña de administrador incorrecta\n");
		Pause;
	}
	else
	{
		printf("Identificado satisfactoriamente como administrador\n");
		int id_admin = *connection_result;
		Pause;

		int option = -1;

		do
		{
			option = MenuAdministracion();

			if (option == 0)
			{
				handleAdminMenuOption0(id_admin, clnt);
			}
			else if(option == 1)
			{
				handleAdminMenuOption1(id_admin, clnt);
			}
			else if(option == 2)
			{
				handleAdminMenuOption2(id_admin, clnt);
			}
			else if(option == 3)
			{
				handleAdminMenuOption3(id_admin, clnt);
			}
			else if(option == 4)
			{
				handleAdminMenuOption4(id_admin, clnt);
			}
			else if(option == 8)
			{
				handleAdminMenuOption8(id_admin, clnt);
			}

		} while (option != 0);
	}
}

int main(int argc, char *argv[])
{
	char *host;

	if (argc < 2)
	{
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];

	CLIENT *clnt;
	int opcion;

	clnt = clnt_create(host, GESTORBIBLIOTECA, GESTORBIBLIOTECA_VER, "tcp");

	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}

	printf("Cliente: Conexión con el servidor adquirida.\n\n");

	do
	{
		opcion = MenuPrincipal();

		if (opcion == 1)
		{
			handleMainMenuOption1(clnt);
		}
		else if(opcion == 2)
		{

		}
		else if(opcion == 3)
		{

		}
		else if(opcion == 4)
		{

		}

	} while (opcion != 0);

	// gestorbiblioteca_1 (host);
	clnt_destroy(clnt);
	exit(0);
}
