/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "GestorBiblioteca.h"
#include <stdlib.h>
#include <time.h>
#include <string.h>
#include <stdio.h>
#include <ctype.h>

#define Cls system("clear")
#define Pause system("read -p \"Pulsa una tecla para continuar..... \" a")
#define MostrarAviso(Texto) \
	{                       \
		printf(Texto);      \
		Pause;              \
	}

void gestorbiblioteca_1(char *host)
{
	CLIENT *clnt;
	int *result_1;
	char conexion_1_arg;
	bool_t *result_2;
	int desconexion_1_arg;
	int *result_3;
	TConsulta cargardatos_1_arg;
	bool_t *result_4;
	int guardardatos_1_arg;
	int *result_5;
	TNuevo nuevolibro_1_arg;
	int *result_6;
	TComRet comprar_1_arg;
	int *result_7;
	TComRet retirar_1_arg;
	bool_t *result_8;
	TOrdenacion ordenar_1_arg;
	int *result_9;
	int nlibros_1_arg;
	int *result_10;
	TConsulta buscar_1_arg;
	TLibro *result_11;
	TPosicion descargar_1_arg;
	int *result_12;
	TPosicion prestar_1_arg;
	int *result_13;
	TPosicion devolver_1_arg;

#ifndef DEBUG
	clnt = clnt_create(host, GESTORBIBLIOTECA, GESTORBIBLIOTECA_VER, "tcp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */

	result_1 = conexion_1(&conexion_1_arg, clnt);
	if (result_1 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	result_2 = desconexion_1(&desconexion_1_arg, clnt);
	if (result_2 == (bool_t *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	result_3 = cargardatos_1(&cargardatos_1_arg, clnt);
	if (result_3 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	result_4 = guardardatos_1(&guardardatos_1_arg, clnt);
	if (result_4 == (bool_t *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	result_5 = nuevolibro_1(&nuevolibro_1_arg, clnt);
	if (result_5 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	result_6 = comprar_1(&comprar_1_arg, clnt);
	if (result_6 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	result_7 = retirar_1(&retirar_1_arg, clnt);
	if (result_7 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	result_8 = ordenar_1(&ordenar_1_arg, clnt);
	if (result_8 == (bool_t *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	result_9 = nlibros_1(&nlibros_1_arg, clnt);
	if (result_9 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	result_10 = buscar_1(&buscar_1_arg, clnt);
	if (result_10 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	result_11 = descargar_1(&descargar_1_arg, clnt);
	if (result_11 == (TLibro *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	result_12 = prestar_1(&prestar_1_arg, clnt);
	if (result_12 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	result_13 = devolver_1(&devolver_1_arg, clnt);
	if (result_13 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
}

int MenuPrincipal()
{
	int Salida;
	do
	{
		Cls;
		printf(" GESTOR BIBLIOTECARIO 1.0 (M. PRINCIPAL)\n");
		printf("*****************************************\n");
		printf("\t1.- M. Administración\n");
		printf("\t2.- Consulta de libros\n");
		printf("\t3.- Prestamos libros\n");
		printf("\t4.- Devolver libros\n");
		printf("\t0.- Salir\n\n");
		printf(" Elige opción: ");
		scanf("%d", &Salida);
		if (Salida < 0 || Salida > 4)
			MostrarAviso("\n\n *** Error en la entrada de Datos.***\n\n");
	} while (Salida < 0 || Salida > 5);
	return Salida;
}

int MenuAdministracion()
{
	int Salida;
	do
	{
		Cls;
		printf(" GESTOR BIBLIOTECARIO 1.0 (M. ADMINISTRACION)\n");
		printf("**********************************************\n");
		printf("\t1.- Cargar datos Biblioteca\n");
		printf("\t2.- Guardar datos Biblioteca\n");
		printf("\t3.- Nuevo libro\n");
		printf("\t4.- Comprar libros\n");
		printf("\t5.- Retirar libros\n");
		printf("\t6.- Ordenar libros\n");
		printf("\t7.- Buscar libros\n");
		printf("\t8.- Listar libros\n");
		printf("\t0.- Salir\n\n");
		printf(" Elige opción: ");
		scanf("%d", &Salida);
		if (Salida < 0 || Salida > 8)
			MostrarAviso("\n\n *** Error en la entrada de Datos.***\n\n");
	} while (Salida < 0 || Salida > 8);
	return Salida;
}

void Formatea(char *Salida, const char *p, int ancho, char Caracter)
{
	Cadena vacia;
	int len = ancho - strlen(p);
	int l = 0, c = 0;

	while (p[l] != '\0')
	{
		if ((unsigned char)p[l] > 128)
			c++;
		l++;
	}
	len += c / 2;

	if (len < 0)
		len = 0;
	for (int i = 0; i < len; i++)
		vacia[i] = Caracter;
	vacia[len] = '\0';

	sprintf(Salida, "%s%s", p, vacia);
}

void MostrarLibro(TLibro *L, int Pos, bool_t Cabecera)
{
	Cadena T, A, B, PI;
	if (Cabecera == TRUE)
	{
		printf("%-*s%-*s%-*s%*s%*s%*s\n", 5, "POS", 58, "TITULO", 18, "ISBN", 4, "DIS", 4, "PRE", 4, "RES");
		printf("     %-*s%-*s%-*s\n", 30, "AUTOR", 28, "PAIS (IDIOMA)", 12, "AÑO");
		Formatea(B, "*", 93, '*');
		printf("%s\n", B);
	}
	Formatea(T, L->Titulo, 58, ' ');
	Formatea(A, L->Autor, 30, ' ');
	strcpy(B, L->Pais);
	strcat(B, " (");
	strcat(B, L->Idioma);
	strcat(B, ")");
	Formatea(PI, B, 28, ' ');
	printf("%-5d%s%-*s%*d%*d%*d\n", Pos + 1, T, 18, L->Isbn, 4, L->NoLibros, 4, L->NoPrestados, 4, L->NoListaEspera);
	printf("     %s%s%-*d\n", A, PI, 12, L->Anio);
}

void handleAdminMenuOption0(int id_admin, CLIENT *clnt)
{
	bool_t *disconnection_result = desconexion_1(&id_admin, clnt);

	if (disconnection_result == (bool_t *)NULL)
	{
		clnt_perror(clnt, "La llamada a la función ha fallado");
		return;
	}

	if (*disconnection_result == TRUE)
	{
		printf("Administrador desconectado\n");
		Pause;
	}
	else if (*disconnection_result == FALSE)
	{
		printf("ID de administrador no coincide con la alojada en el servidor, \
					se procederá a cerrar su sesión\n");
		Pause;
		exit(1);
	}
}

void handleAdminMenuOption1(int id_admin, CLIENT *clnt)
{
	Cls;

	Cadena file_name;

	printf("Introduce el nombre del fichero de datos: ");
	__fpurge(stdin);
	scanf("%s", file_name);

	TConsulta query;
	query.Ida = id_admin;
	strcpy(query.Datos, file_name);

	int *result = cargardatos_1(&query, clnt);

	if (result == (int *)NULL)
	{
		clnt_perror(clnt, "La llamada a la función ha fallado");
		return;
	}

	if(*result == -1)
	{
		printf("Ya hay un usuario identificado como administrador, o bien el ID de administrador " \
		"no coincide.\n");
		Pause;
	}
	else if(*result == 0)
	{
		printf("Error al cargar los datos de la biblioteca\n");
		Pause;
	}
	else if(*result == 1)
	{
		printf("Datos de la biblioteca cargados correctamente\n");
		Pause;
	}
}

void handleAdminMenuOption8(int id_admin, CLIENT *clnt)
{
	Cls;

	int *number_of_books = nlibros_1(&id_admin, clnt);

	if (number_of_books == (int *)NULL)
	{
		clnt_perror(clnt, "La llamada a la función ha fallado");
		return;
	}

	if(*number_of_books == 0)
	{
		printf("No hay libros cargados en la biblioteca.\n");
		Pause;
		return;
	}

	printf("Libros en la biblioteca: %d\n", *number_of_books);

	TPosicion position;
	position.Ida = id_admin;

	for (int i = 0; i < *number_of_books; i++)
	{
		position.Pos = i;

		TLibro *book = descargar_1(&position, clnt);

		if (book == (TLibro *)NULL)
		{
			clnt_perror(clnt, "La llamada a la función ha fallado");
			return;
		}

		if(i == 0)
		{
			MostrarLibro(book, i, TRUE);
		}
		else
		{
			MostrarLibro(book, i, FALSE);
		}
	}
	
	Pause;
}

void handleMainMenuOption1(CLIENT *clnt)
{
	Cls;

	Cadena password;

	printf("Por favor inserte la contraseña de Administración: ");
	__fpurge(stdin);
	scanf("%s", password);

	int *connection_result = conexion_1(&password, clnt);

	if (connection_result == (int *)NULL)
	{
		clnt_perror(clnt, "La llamada a la función ha fallado");
		return;
	}

	if (*connection_result == -1)
	{
		printf("Ya existe un usuario identificado como administrador\n");
		Pause;
	}
	else if (*connection_result == -2)
	{
		printf("Contraseña de administrador incorrecta\n");
		Pause;
	}
	else
	{
		printf("Identificado satisfactoriamente como administrador\n");
		int id_admin = *connection_result;
		Pause;

		int option = -1;

		do
		{
			option = MenuAdministracion();

			if (option == 0)
			{
				handleAdminMenuOption0(id_admin, clnt);
			}
			else if(option == 1)
			{
				handleAdminMenuOption1(id_admin, clnt);
			}
			else if(option == 8)
			{
				handleAdminMenuOption8(id_admin, clnt);
			}

		} while (option != 0);
	}
}

int main(int argc, char *argv[])
{
	char *host;

	if (argc < 2)
	{
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];

	CLIENT *clnt;
	int opcion;

	clnt = clnt_create(host, GESTORBIBLIOTECA, GESTORBIBLIOTECA_VER, "tcp");

	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}

	printf("Cliente: Conexión con el servidor adquirida.\n\n");

	do
	{
		opcion = MenuPrincipal();

		if (opcion == 1)
		{
			handleMainMenuOption1(clnt);
		}
		else if(opcion == 2)
		{

		}
		else if(opcion == 3)
		{

		}
		else if(opcion == 4)
		{

		}

	} while (opcion != 0);

	// gestorbiblioteca_1 (host);
	clnt_destroy(clnt);
	exit(0);
}
